MTL-1501 Fail to Disk
Cray-HPE/metal-ipxe pull request #24
Opened 2021-11-29 23:07 UTC by rustydb

#### Summary and Scope

- Fixes MTL-1501
- Relates to MTL-1572

##### Issue Type

- Bugfix Pull Request

This change adds new logging and earlier exits to the metal iPXE configuration. The new early exits will print the error cause, wait for 5 seconds, and then bail. The bail exits the ROM and causes the BIOS to move onto the next boot option.
    
Some servers may fall to BIOS if their boot order is not configured, or if they have a feature-toggle on for exit on failure (rare).

#### Prerequisites

- [ ] I have included documentation in my PR (or it is not required)
- [ ] I tested this on internal system (x) (if yes, please include results or a description of the test)
 

#### Idempotency
 

 
#### Risks and Mitigations

2021-11-29 23:08 UTC, heemstra requested changes

2021-11-29 23:08 UTC, heemstra commented on .github/workflows/merge-strategy.yml
> +name: Merge Strategy
This should be a separate PR. You wouldn't want it caught up in a revert.

2021-11-30 00:50 UTC, rustydb commented on .github/workflows/merge-strategy.yml
> +name: Merge Strategy
Thanks for noticing. For what it is worth I actually didn't mean to include this. I created this branch off my local block-merge-commits branch and didn't pay attention to the overzealous include.

Will factor this out.

2021-11-30 00:52 UTC, rustydb commented
I'm not sure why but the cmdline isn't printing anymore, I stared at the diff for 5minutes and couldn't figure out what happened to change it. Perhaps fresh eyes in the AM will figure it out:
```bash
64 bytes from 10.1.1.2: seq=1
Successfully called home; deployment server is reachable
http://pit/ncn-w003/initrd.img.xz... ok
initrd.img.xz : 52780376 bytes
http://pit/ncn-w003/kernel... ok

initramFS and kernel succesfully downloaded.

Starting up...
```
(cmdline should dump before `Starting up...` is printed)

2021-11-30 00:53 UTC, rustydb commented on .github/workflows/merge-strategy.yml
> +name: Merge Strategy
(for deeper context, this file is already in `main` and I didn't rebase on the latest main when I pushed this)

2021-11-30 19:26 UTC, heemstra approved these changes

2021-11-30 19:26 UTC, merged